apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/redhat-appstudio-qe/multi-platform-test-prod?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-event: '[pull_request]'
    pipelinesascode.tekton.dev/on-target-branch: '[main]'
  labels:
    appstudio.openshift.io/application: e2e-multi-platform-test-prod
    appstudio.openshift.io/component: e2e-multi-platform-test
    pipelines.appstudio.openshift.io/type: build
  name: e2e-multi-platform-test-on-pull-request
  namespace: dev-release-team-tenant
spec:
  params:
  - name: dockerfile
    value: docker/Dockerfile
  - name: git-url
    value: '{{source_url}}'
  - name: image-expires-after
    value: 5d
  - name: output-image
    value: quay.io/redhat-user-workloads-stage/dev-release-team-tenant/e2e-multi-platform-test-prod/e2e-multi-platform-test:on-pr-{{revision}}
  - name: path-context
    value: .
  - name: revision
    value: '{{revision}}'
  pipelineRef:
    name: build-pipeline
  workspaces:
    - name: workspace-amd64
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    - name: workspace-arm64
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    - name: workspace-ppc64le
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    - name: workspace-s390x
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    - name: git-auth
      secret:
        secretName: '{{ git_auth_secret }}'
